In [1]:

import pandas as pd
from sklearn import svm
from sklearn.model_selection import GridSearchCV
import os
import matplotlib.pyplot as plt
from skimage.transform import resize
from skimage.io import imread
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
import pickle
from sklearn.metrics import top_k_accuracy_score

**NOTE** : Please enter Category Names same as folder name

In [4]:

Categories=['ant','beaver', 'cup','ewer', 'lamp','pizza', 'rhino','elephant','dolphin','crab']

# main_folder_path = 'E:/University/Tarbiat Modarres/Term1/Machin Learning/Article/Code/data/caltech-101/101_ObjectCategories'

# Categories = os.listdir(main_folder_path)
# Categories

#   SVM Kernel

Loading all the images and creating a DataFrame

If you have your images in your google drive, simply mount the google Drive and copy the path of the folder containing all the Category images and Change the datadir variable to that path

In [5]:
flat_data_arr=[]
target_arr=[]
#please use datadir='/content' if the files are upload on to google collab
#else mount the drive and give path of the parent-folder containing all category images folders.
datadir='E:/University/Tarbiat Modarres/Term1/Machin Learning/Article/Code/data/caltech-101/101_ObjectCategories' 
for i in Categories:
  print(f'loading... category : {i}')
  path=os.path.join(datadir,i)
  for img in os.listdir(path):
    img_array=imread(os.path.join(path,img))
    img_resized=resize(img_array,(30,30,3))
    flat_data_arr.append(img_resized.flatten())
    target_arr.append(Categories.index(i))
  print(f'loaded category:{i} successfully')
flat_data=np.array(flat_data_arr)
target=np.array(target_arr)
df=pd.DataFrame(flat_data)
df['Target']=target
df

loading... category : ant
loaded category:ant successfully
loading... category : beaver
loaded category:beaver successfully
loading... category : cup
loaded category:cup successfully
loading... category : ewer
loaded category:ewer successfully
loading... category : lamp
loaded category:lamp successfully
loading... category : pizza
loaded category:pizza successfully
loading... category : rhino
loaded category:rhino successfully
loading... category : elephant
loaded category:elephant successfully
loading... category : dolphin
loaded category:dolphin successfully
loading... category : crab
loaded category:crab successfully

,0,1,2,3,4,5,6,7,8,9,...,2691,2692,2693,2694,2695,2696,2697,2698,2699,Target
0,9.809019e-02,0.102507,0.188686,9.871258e-02,1.051867e-01,1.878433e-01,0.114509,0.123648,0.177509,3.254690e-01,...,0.646957,0.610431,0.612689,0.649940,0.602855,0.611951,6.427757e-01,0.595683,0.603774,0
1,5.801917e-08,0.000014,0.000020,2.030937e-04,9.159553e-04,8.900180e-04,0.015372,0.018944,0.018630,1.197845e-01,...,0.007819,0.009301,0.005415,0.000046,0.000077,0.000121,8.264312e-08,0.000005,0.000002,0
2,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,1.875051e-09,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0
3,1.635179e-01,0.300259,0.237979,2.105695e-01,4.652854e-01,3.364635e-01,0.215489,0.469478,0.338418,2.154944e-01,...,0.208688,0.469678,0.341051,0.207696,0.463160,0.336624,1.672291e-01,0.302272,0.226954,0
4,0.000000e+00,0.000000,0.000000,6.592130e-07,6.592130e-07,6.592130e-07,0.002352,0.002352,0.002352,1.957863e-01,...,0.001977,0.001977,0.001977,0.000002,0.000002,0.000002,0.000000e+00,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,4.758968e-01,0.247862,0.484286,5.022639e-01,2.811836e-01,5.152581e-01,0.486386,0.285039,0.523255,4.946682e-01,...,0.419105,0.496122,0.517652,0.312572,0.393984,0.434915,1.530300e-01,0.223305,0.243674,9
601,1.284211e-01,0.165072,0.205863,1.664843e-01,2.054430e-01,2.381510e-01,0.204826,0.247424,0.268128,2.117930e-01,...,0.269100,0.261999,0.251272,0.167006,0.217366,0.229693,1.554699e-01,0.208980,0.222792,9
602,1.808395e-01,0.670036,0.922359,1.734240e-01,6.508871e-01,8.980753e-01,0.175239,0.609393,0.830403,1.875628e-01,...,0.197551,0.662593,0.903688,0.177837,0.670540,0.923457,1.676727e-01,0.672826,0.917277,9
603,2.542317e-01,0.310003,0.314955,2.524143e-01,3.019822e-01,2.852427e-01,0.407613,0.437538,0.392011,4.551463e-01,...,0.282428,0.348818,0.389705,0.322992,0.332780,0.350641,1.617047e-01,0.185950,0.192772,9
604,6.344010e-01,0.769249,0.773051,6.362124e-01,7.694328e-01,7.776095e-01,0.637188,0.768719,0.783525,6.314066e-01,...,0.669289,0.749115,0.737641,0.662998,0.741602,0.737376,6.670484e-01,0.739352,0.736740,9

Splitting the data into training and testing data

In [6]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=77,stratify=y)
print('Splitted Successfully')

Splitted Successfully

This Part of code may take a while for training the data using SVC model

In [7]:
param_grid={'C':[0.1,1,10,100],'gamma':[0.0001,0.001,0.1,1],'kernel':['rbf','poly']}
svc=svm.SVC(probability=True)
print("The training of the model is started, please wait for while as it may take few minutes to complete")
model=GridSearchCV(svc,param_grid)
model.fit(x_train,y_train)
print('The Model is trained well with the given images')
model.best_params_

The training of the model is started, please wait for while as it may take few minutes to complete
The Model is trained well with the given images

{'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}

Predicting our testing data

In [8]:
y_pred=model.predict(x_test)
print("The predicted Data is :")
y_pred

The predicted Data is :

array([0, 3, 3, 2, 9, 1, 8, 2, 5, 3, 9, 4, 4, 8, 1, 3, 9, 6, 1, 4, 3, 7,
       3, 5, 7, 7, 3, 5, 3, 3, 7, 1, 1, 0, 4, 8, 9, 9, 6, 6, 9, 9, 8, 7,
       3, 5, 4, 7, 5, 7, 9, 8, 7, 6, 9, 3, 9, 9, 1, 8, 4, 6, 3, 2, 3, 3,
       0, 8, 2, 2, 8, 8, 5, 3, 7, 2, 3, 8, 4, 1, 9, 8, 1, 8, 8, 5, 7, 2,
       3, 7, 5, 6, 5, 1, 9, 3, 9, 8, 3, 0, 3, 9, 2, 1, 6, 2, 6, 6, 1, 4,
       4, 3, 2, 2, 7, 5, 0, 6, 6, 9, 6])

In [9]:
print("The actual data is:")
np.array(y_test)

The actual data is:

array([0, 3, 3, 4, 9, 1, 8, 0, 5, 7, 9, 4, 4, 8, 2, 3, 3, 9, 0, 2, 2, 1,
       4, 5, 7, 7, 2, 5, 6, 3, 6, 1, 1, 4, 7, 8, 9, 4, 7, 6, 6, 9, 3, 7,
       1, 5, 7, 3, 5, 1, 2, 8, 7, 8, 1, 3, 5, 2, 3, 4, 4, 6, 2, 8, 3, 2,
       3, 8, 9, 9, 8, 8, 5, 3, 4, 2, 3, 8, 6, 1, 9, 7, 0, 8, 8, 5, 6, 2,
       3, 7, 5, 9, 9, 9, 6, 3, 1, 0, 3, 0, 7, 9, 0, 2, 6, 6, 7, 0, 8, 4,
       4, 4, 9, 3, 9, 5, 5, 7, 6, 9, 6])

In [10]:
print("The decision_scores is:")

decision_scores = model.decision_function(x_test)
decision_scores

The decision_scores is:

array([[ 9.30687009,  1.73460614,  6.28341803, ...,  3.73952817,
         8.27564737,  7.26032825],
       [ 6.25815813,  3.7687932 ,  8.29003597, ..., -0.30271537,
         7.24365638,  0.7121095 ],
       [ 3.80018816,  7.27316067,  2.73934354, ...,  5.17115197,
         1.73983324,  8.28378825],
       ...,
       [ 6.20114644,  7.2690514 ,  2.83609312, ...,  8.28676746,
         1.73171137,  5.1283624 ],
       [ 6.25075235,  7.27440517,  1.75306375, ...,  3.82674246,
         1.73360185,  9.29813342],
       [ 5.18233537,  6.21548165,  0.71348264, ...,  8.3003468 ,
         0.699525  ,  7.28368714]])

In [11]:
print(f"The model is {top_k_accuracy_score(y_test, decision_scores, k=5)*100}% accurate")
print("\nK=5")

The model is 89.25619834710744% accurate

K=5

In [12]:
#classification_report(y_pred,y_test)
print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")
#confusion_matrix(y_pred,y_test)

The model is 49.586776859504134% accurate

# SVM with WM (Wavelet Moments) Image Filter

In [13]:
import cv2
import pywt

In [14]:
def extract_wm_features(image):
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    coeffs = pywt.wavedec2(gray_image, 'db1', level=4)
    
    wm_features = []
    for level in range(1, len(coeffs)):
        for direction in range(0, len(coeffs[level])):
            wm = np.mean(np.abs(coeffs[level][direction]))
            wm_features.append(wm)
    
    return np.array(wm_features)

In [15]:
flat_data_arr=[]
target_arr=[]
#please use datadir='/content' if the files are upload on to google collab
#else mount the drive and give path of the parent-folder containing all category images folders.
datadir='E:/University/Tarbiat Modarres/Term1/Machin Learning/Article/Code/data/caltech-101/101_ObjectCategories' 
for i in Categories:
  print(f'loading... category : {i}')
  path=os.path.join(datadir,i)
  for img in os.listdir(path):
    img_array=cv2.imread(os.path.join(path,img))
    img_resized = cv2.resize(img_array, (40, 40))

    wm_features = extract_wm_features(img_resized)
    flat_data_arr.append(wm_features)
    target_arr.append(Categories.index(i))
  print(f'loaded category:{i} successfully')
flat_data=np.array(flat_data_arr)
target=np.array(target_arr)
df=pd.DataFrame(flat_data)
df['Target']=target
df

loading... category : ant
loaded category:ant successfully
loading... category : beaver
loaded category:beaver successfully
loading... category : cup
loaded category:cup successfully
loading... category : ewer
loaded category:ewer successfully
loading... category : lamp
loaded category:lamp successfully
loading... category : pizza
loaded category:pizza successfully
loading... category : rhino
loaded category:rhino successfully
loading... category : elephant
loaded category:elephant successfully
loading... category : dolphin
loaded category:dolphin successfully
loading... category : crab
loaded category:crab successfully

,0,1,2,3,4,5,6,7,8,9,10,11,Target
0,167.715278,131.729167,122.576389,83.830,91.180,52.070,32.6850,35.9950,19.2550,11.49250,14.10250,8.59000,0
1,188.902778,126.027778,94.902778,99.790,95.180,47.120,40.5100,36.8250,25.0250,19.40500,15.96250,14.48500,0
2,210.312500,193.868056,30.020833,122.540,85.580,71.940,42.2800,32.8050,25.8550,22.47250,19.28500,17.64500,0
3,105.298611,64.298611,35.826389,120.080,83.940,39.750,57.3650,51.1100,17.4450,27.91000,27.14750,10.06250,0
4,294.013889,284.236111,116.805556,160.880,158.490,104.880,54.9800,53.5300,41.0750,24.59750,23.92500,20.87750,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,152.590278,112.493056,46.548611,92.935,99.305,69.005,47.4575,60.2475,38.0525,25.51875,28.75375,19.40875,9
601,84.444444,49.597222,44.513889,52.005,52.705,43.245,32.1825,52.0125,25.5025,19.10375,24.16625,17.54375,9
602,83.958333,96.930556,43.930556,73.900,85.620,43.880,42.6850,45.5400,28.0500,25.41250,20.80500,17.59250,9
603,125.708333,110.138889,59.694444,63.795,79.675,53.395,51.3625,47.6775,32.4025,29.74125,27.94625,24.92125,9
604,118.138889,121.097222,59.847222,74.305,59.945,29.555,34.5275,31.7625,22.1475,17.23375,15.18875,13.07875,9

In [16]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=77,stratify=y)
print('Splitted Successfully')

Splitted Successfully

In [17]:
param_grid={'C':[0.1,1,10,100],'gamma':[0.0001,0.001,0.1,1],'kernel':['rbf','poly']}
svc=svm.SVC(probability=True)
print("The training of the model is started, please wait for while as it may take few minutes to complete")
model=GridSearchCV(svc,param_grid)
model.fit(x_train,y_train)
print('The Model is trained well with the given images')
model.best_params_

The training of the model is started, please wait for while as it may take few minutes to complete
The Model is trained well with the given images

{'C': 0.1, 'gamma': 0.0001, 'kernel': 'poly'}

In [18]:
y_pred=model.predict(x_test)
print("The predicted Data is :")
y_pred

The predicted Data is :

array([6, 1, 8, 3, 8, 9, 3, 0, 6, 6, 9, 3, 3, 8, 8, 8, 2, 8, 8, 0, 9, 8,
       4, 8, 7, 8, 3, 6, 6, 8, 8, 0, 8, 3, 6, 8, 8, 3, 7, 0, 9, 9, 8, 8,
       9, 5, 9, 3, 9, 3, 3, 8, 7, 7, 8, 3, 9, 8, 3, 4, 4, 8, 8, 9, 8, 9,
       8, 8, 9, 8, 8, 8, 8, 3, 3, 8, 3, 8, 8, 8, 7, 8, 8, 8, 7, 2, 8, 2,
       8, 1, 8, 8, 5, 5, 8, 7, 5, 0, 3, 0, 3, 3, 5, 7, 6, 8, 3, 3, 8, 4,
       3, 8, 7, 8, 5, 8, 3, 0, 3, 5, 3])

In [19]:
print("The actual data is:")
np.array(y_test)

The actual data is:

array([0, 3, 3, 4, 9, 1, 8, 0, 5, 7, 9, 4, 4, 8, 2, 3, 3, 9, 0, 2, 2, 1,
       4, 5, 7, 7, 2, 5, 6, 3, 6, 1, 1, 4, 7, 8, 9, 4, 7, 6, 6, 9, 3, 7,
       1, 5, 7, 3, 5, 1, 2, 8, 7, 8, 1, 3, 5, 2, 3, 4, 4, 6, 2, 8, 3, 2,
       3, 8, 9, 9, 8, 8, 5, 3, 4, 2, 3, 8, 6, 1, 9, 7, 0, 8, 8, 5, 6, 2,
       3, 7, 5, 9, 9, 9, 6, 3, 1, 0, 3, 0, 7, 9, 0, 2, 6, 6, 7, 0, 8, 4,
       4, 4, 9, 3, 9, 5, 5, 7, 6, 9, 6])

In [20]:
#classification_report(y_pred,y_test)
print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")
#confusion_matrix(y_pred,y_test)

The model is 26.446280991735538% accurate

# SVM with LBP (Local Binary Pattern) Image Filter

In [21]:

def extract_lbp_features(photo):
  def assign_bit(picture, x, y, c):   #comparing bit with threshold value of centre pixel
      bit = 0  
      try:          
          if picture[x][y] >= c: 
              bit = 1         
      except: 
          pass
      return bit 
  def local_bin_val(picture, x, y):  #calculating local binary pattern value of a pixel
      eight_bit_binary = []
      centre = picture[x][y] 
      powers = [1, 2, 4, 8, 16, 32, 64, 128] 
      decimal_val = 0
      #starting from top right,assigning bit to pixels clockwise 
      eight_bit_binary.append(assign_bit(picture, x-1, y + 1,centre)) 
      eight_bit_binary.append(assign_bit(picture, x, y + 1, centre)) 
      eight_bit_binary.append(assign_bit(picture, x + 1, y + 1, centre)) 
      eight_bit_binary.append(assign_bit(picture, x + 1, y, centre)) 
      eight_bit_binary.append(assign_bit(picture, x + 1, y-1, centre)) 
      eight_bit_binary.append(assign_bit(picture, x, y-1, centre)) 
      eight_bit_binary.append(assign_bit(picture, x-1, y-1, centre)) 
      eight_bit_binary.append(assign_bit(picture, x-1, y, centre))     
      #calculating decimal value of the 8-bit binary number
      for i in range(len(eight_bit_binary)): 
          decimal_val += eight_bit_binary[i] * powers[i] 
            
      return decimal_val 
  m, n, _ = photo.shape 
  gray_scale = cv2.cvtColor(photo, cv2.COLOR_BGR2GRAY)  #converting image to grayscale
  lbp_photo = np.zeros((m, n),np.uint8) 
  # converting image to lbp
  for i in range(0,m): 
      for j in range(0,n): 
          lbp_photo[i, j] = local_bin_val(gray_scale, i, j) 
     
  return lbp_photo.flatten()

In [22]:
flat_data_arr=[]
target_arr=[]
#please use datadir='/content' if the files are upload on to google collab
#else mount the drive and give path of the parent-folder containing all category images folders.
datadir='E:/University/Tarbiat Modarres/Term1/Machin Learning/Article/Code/data/caltech-101/101_ObjectCategories' 
for i in Categories:
  print(f'loading... category : {i}')
  path=os.path.join(datadir,i)
  for img in os.listdir(path):
    img_array=cv2.imread(os.path.join(path,img))
    img_resized = cv2.resize(img_array, (30, 30))

    wm_features = extract_lbp_features(img_resized)
    flat_data_arr.append(wm_features)
    target_arr.append(Categories.index(i))
  print(f'loaded category:{i} successfully')
flat_data=np.array(flat_data_arr)
target=np.array(target_arr)
df=pd.DataFrame(flat_data)
df['Target']=target
df

loading... category : ant

loaded category:ant successfully
loading... category : beaver
loaded category:beaver successfully
loading... category : cup
loaded category:cup successfully
loading... category : ewer
loaded category:ewer successfully
loading... category : lamp
loaded category:lamp successfully
loading... category : pizza
loaded category:pizza successfully
loading... category : rhino
loaded category:rhino successfully
loading... category : elephant
loaded category:elephant successfully
loading... category : dolphin
loaded category:dolphin successfully
loading... category : crab
loaded category:crab successfully

,0,1,2,3,4,5,6,7,8,9,...,891,892,893,894,895,896,897,898,899,Target
0,245,239,223,199,195,199,195,195,195,195,...,227,195,227,67,128,224,227,195,192,0
1,255,255,14,0,60,62,14,8,56,48,...,227,227,227,227,227,128,227,227,224,0
2,255,255,255,255,255,255,255,255,207,223,...,224,225,227,227,227,227,227,227,224,0
3,127,31,191,255,254,28,62,62,62,60,...,227,227,227,227,227,195,193,227,224,0
4,255,255,255,14,0,42,6,6,46,56,...,35,163,227,227,224,227,227,227,224,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,150,105,183,201,246,104,63,10,20,60,...,130,0,32,35,129,224,224,96,224,9
601,31,30,2,0,43,148,107,148,255,95,...,227,0,224,99,3,128,226,65,160,9
602,161,243,225,247,237,251,85,239,213,237,...,0,34,2,2,0,35,160,96,224,9
603,0,246,2,0,32,44,56,54,14,8,...,163,2,0,226,64,35,0,32,160,9
604,143,221,255,255,255,253,255,253,253,249,...,32,96,98,32,224,227,225,224,224,9

In [23]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=77,stratify=y)
print('Splitted Successfully')

Splitted Successfully

In [24]:
param_grid={'C':[0.1,1,10,100],'gamma':[0.0001,0.001,0.1,1],'kernel':['rbf','poly']}
svc=svm.SVC(probability=True)
print("The training of the model is started, please wait for while as it may take few minutes to complete")
model=GridSearchCV(svc,param_grid)
model.fit(x_train,y_train)
print('The Model is trained well with the given images')
model.best_params_

The training of the model is started, please wait for while as it may take few minutes to complete
The Model is trained well with the given images

{'C': 0.1, 'gamma': 0.0001, 'kernel': 'poly'}

In [25]:
y_pred=model.predict(x_test)
print("The predicted Data is :")
y_pred

The predicted Data is :

array([8, 4, 4, 7, 7, 3, 7, 2, 3, 3, 9, 3, 3, 3, 8, 3, 3, 3, 8, 7, 3, 6,
       4, 9, 0, 3, 2, 3, 6, 2, 7, 6, 3, 4, 3, 9, 3, 4, 2, 6, 3, 4, 4, 3,
       8, 3, 3, 3, 6, 7, 2, 3, 7, 7, 9, 3, 6, 9, 7, 3, 5, 2, 4, 3, 3, 7,
       2, 6, 9, 2, 9, 9, 8, 8, 7, 4, 3, 8, 4, 3, 9, 3, 2, 8, 8, 7, 3, 2,
       4, 9, 3, 3, 0, 3, 3, 0, 4, 0, 3, 8, 3, 1, 2, 3, 9, 6, 7, 3, 0, 3,
       4, 2, 3, 3, 8, 9, 6, 3, 6, 3, 6])

In [26]:
print("The actual data is:")
np.array(y_test)

The actual data is:

array([0, 3, 3, 4, 9, 1, 8, 0, 5, 7, 9, 4, 4, 8, 2, 3, 3, 9, 0, 2, 2, 1,
       4, 5, 7, 7, 2, 5, 6, 3, 6, 1, 1, 4, 7, 8, 9, 4, 7, 6, 6, 9, 3, 7,
       1, 5, 7, 3, 5, 1, 2, 8, 7, 8, 1, 3, 5, 2, 3, 4, 4, 6, 2, 8, 3, 2,
       3, 8, 9, 9, 8, 8, 5, 3, 4, 2, 3, 8, 6, 1, 9, 7, 0, 8, 8, 5, 6, 2,
       3, 7, 5, 9, 9, 9, 6, 3, 1, 0, 3, 0, 7, 9, 0, 2, 6, 6, 7, 0, 8, 4,
       4, 4, 9, 3, 9, 5, 5, 7, 6, 9, 6])

In [27]:
#classification_report(y_pred,y_test)
print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")
#confusion_matrix(y_pred,y_test)

The model is 23.96694214876033% accurate

# SVM with Corr Image Filter

In [28]:
from scipy.ndimage import correlate

In [29]:
def extract_corr_features(image):
   
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    corr_image = correlate(gray_image, np.array([[1, 1, 1], [1, -8, 1], [1, 1, 1]]), mode='constant', cval=0.0)
    
    corr_features = corr_image.flatten()
    
    return corr_features

In [30]:
flat_data_arr=[]
target_arr=[]
#please use datadir='/content' if the files are upload on to google collab
#else mount the drive and give path of the parent-folder containing all category images folders.
datadir='E:/University/Tarbiat Modarres/Term1/Machin Learning/Article/Code/data/caltech-101/101_ObjectCategories' 
for i in Categories:
  print(f'loading... category : {i}')
  path=os.path.join(datadir,i)
  for img in os.listdir(path):
    img_array=cv2.imread(os.path.join(path,img))
    img_resized = cv2.resize(img_array, (30, 30))

    wm_features = extract_corr_features(img_resized)
    flat_data_arr.append(wm_features)
    target_arr.append(Categories.index(i))
  print(f'loaded category:{i} successfully')
flat_data=np.array(flat_data_arr)
target=np.array(target_arr)
df=pd.DataFrame(flat_data)
df['Target']=target
df

loading... category : ant
loaded category:ant successfully
loading... category : beaver

loaded category:beaver successfully
loading... category : cup
loaded category:cup successfully
loading... category : ewer
loaded category:ewer successfully
loading... category : lamp
loaded category:lamp successfully
loading... category : pizza
loaded category:pizza successfully
loading... category : rhino
loaded category:rhino successfully
loading... category : elephant
loaded category:elephant successfully
loading... category : dolphin
loaded category:dolphin successfully
loading... category : crab
loaded category:crab successfully

,0,1,2,3,4,5,6,7,8,9,...,891,892,893,894,895,896,897,898,899,Target
0,117,189,7,245,92,138,128,109,89,96,...,111,67,77,27,253,49,74,58,250,0
1,0,3,112,185,105,134,57,16,93,146,...,184,184,184,184,186,130,51,1,0,0
2,0,0,0,0,0,0,1,105,186,235,...,3,119,11,6,1,0,0,0,0,0
3,105,69,151,152,154,145,154,152,153,154,...,159,156,155,157,160,155,146,83,108,0
4,0,0,99,45,89,7,251,250,2,253,...,255,2,3,3,129,122,124,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,28,203,245,203,233,193,191,228,204,26,...,10,69,65,10,144,133,143,179,246,9
601,106,131,23,205,91,77,119,84,222,150,...,123,204,239,243,90,64,120,41,133,9
602,10,39,0,189,179,190,112,34,83,165,...,215,233,163,143,47,4,40,107,74,9
603,147,137,68,108,15,109,26,189,35,195,...,30,87,255,79,20,74,77,0,76,9
604,122,213,234,232,235,229,233,226,241,239,...,157,186,194,190,191,225,214,220,142,9

In [31]:
param_grid={'C':[0.1,1,10,100],'gamma':[0.0001,0.001,0.1,1],'kernel':['rbf','poly']}
svc=svm.SVC(probability=True)
print("The training of the model is started, please wait for while as it may take few minutes to complete")
model=GridSearchCV(svc,param_grid)
model.fit(x_train,y_train)
print('The Model is trained well with the given images')
model.best_params_

The training of the model is started, please wait for while as it may take few minutes to complete
The Model is trained well with the given images

{'C': 0.1, 'gamma': 0.0001, 'kernel': 'poly'}

In [32]:
y_pred=model.predict(x_test)
print("The predicted Data is :")
y_pred

The predicted Data is :

array([8, 4, 4, 7, 7, 3, 7, 2, 3, 3, 9, 3, 3, 3, 8, 3, 3, 3, 8, 7, 3, 6,
       4, 9, 0, 3, 2, 3, 6, 2, 7, 6, 3, 4, 3, 9, 3, 4, 2, 6, 3, 4, 4, 3,
       8, 3, 3, 3, 6, 7, 2, 3, 7, 7, 9, 3, 6, 9, 7, 3, 5, 2, 4, 3, 3, 7,
       2, 6, 9, 2, 9, 9, 8, 8, 7, 4, 3, 8, 4, 3, 9, 3, 2, 8, 8, 7, 3, 2,
       4, 9, 3, 3, 0, 3, 3, 0, 4, 0, 3, 8, 3, 1, 2, 3, 9, 6, 7, 3, 0, 3,
       4, 2, 3, 3, 8, 9, 6, 3, 6, 3, 6])

In [33]:
print("The actual data is:")
np.array(y_test)

The actual data is:

array([0, 3, 3, 4, 9, 1, 8, 0, 5, 7, 9, 4, 4, 8, 2, 3, 3, 9, 0, 2, 2, 1,
       4, 5, 7, 7, 2, 5, 6, 3, 6, 1, 1, 4, 7, 8, 9, 4, 7, 6, 6, 9, 3, 7,
       1, 5, 7, 3, 5, 1, 2, 8, 7, 8, 1, 3, 5, 2, 3, 4, 4, 6, 2, 8, 3, 2,
       3, 8, 9, 9, 8, 8, 5, 3, 4, 2, 3, 8, 6, 1, 9, 7, 0, 8, 8, 5, 6, 2,
       3, 7, 5, 9, 9, 9, 6, 3, 1, 0, 3, 0, 7, 9, 0, 2, 6, 6, 7, 0, 8, 4,
       4, 4, 9, 3, 9, 5, 5, 7, 6, 9, 6])

In [34]:
#classification_report(y_pred,y_test)
print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")
#confusion_matrix(y_pred,y_test)

The model is 23.96694214876033% accurate